### ISSUE TITLE
com.google.cloud.Identity does not support the new IAM deleted user syntax 

### ISSUE THREAD

**Issue by clementdenis** [googleapis/java-core#322] opened 2020-11-02 11:22 UTC
The new IAM deleted user syntax is not supported by com.google.cloud.Identity:
https://cloud.google.com/iam/docs/policies#handle-deleted-members

#### Environment details

1. Affects the Core library and all dependant libraries
2. OS type and version: any
3. Java version: any
4. google-cloud-core version(s): any

#### Steps to reproduce

  1. Try to parse a deleted user string with Identity.valueOf
  2. This results either to a stacktrace (1.74.0 and lower) or a DELETED identity type (1.75.0 and higher)

#### Code example

```java
Identity identity = Identity.valueOf("deleted:user:donald@example.com?uid=234567890123456789012");
System.out.println("type = " + identity.getType());
System.out.println("value = " + identity.getValue());
```

#### Stack trace
1.74.0 and lower
```
java.lang.IllegalArgumentException: Illegal identity string: "deleted:user:donald@example.com?uid=234567890123456789012"
```

1.75.0 and higher
```
type = DELETED
value = user:donald@example.com?uid=234567890123456789012
```

The "fix" is caused by an unrelated change: https://github.com/googleapis/java-core/commit/24667e5c27ab71bd217d6667c1cb0affefe09b13

#### External references such as API reference guides

https://cloud.google.com/iam/docs/policies#handle-deleted-members

**Comment by athakor** [comment] 2020-11-12 08:55
@clementdenis 
 
The fixed was already made [here](https://github.com/googleapis/google-cloud-java/pull/5029), so i would recommend you to used `1.75.0` and `higher`.

 **FYI**, The output of the split can not be longer than `2`, It will throw an `IllegalArgumentException` if there's more parts than we expect.

**Comment by athakor** [comment] 2020-11-12 09:19
i am closing this issue, as it's not able to reproduce in latest version.

**Closed by athakor** 2020-11-12 09:19 UTC
Labels: priority: p2, status: investigating, type: bug
